### ISSUE TITLE
Getting repeated logs in log file.

### ISSUE THREAD

**Issue by viky28** [feeltheajf/trufflehog3#11]
i am passing this below command to check github repo url

trufflehog3 --branch="master" --no-entropy --skip-paths="(.*\/)?vendor|test|wordpress|node_modules\/(.*\/)?" --format=text  **git_hub_repo_url** > **output url**
in output file i am getting multiple repeats 
Could somebody help me why i am getting repeated secrets multiple times in log file.

**Comment by feeltheajf** [comment]
@viky28, 

In trufflehog deduplication logic is intentionally left for the end user.

The secrets could be found both in history and in the current repo state, you can disable one of the checks by using corresponding flags.

It is also possible that a secret is found using both high entropy check and regex search, you can disable one of them if you want or supply custom regex patterns

**Comment by viky28** [comment]
@feeltheajf 
1. Using  **--no-entropy(not using --no-regex flag)** with **--no-current (not using --no-history flag)** giving result with **Barnch,Commit and hash as null.**
2. Using **--no-entropy(not using --no-regex flag)** with **--no-history (not using --no-current flag)** giving result with **repeated logs**

**Comment by feeltheajf** [comment]
Hi @viky28 

Please make sure you don't have overlapping rules. Otherwise, please give me a minimal example for reproducing this issue
