### ISSUE TITLE
Version 2.x no longer includes line numbers in project

### ISSUE THREAD

**Issue by corang** [feeltheajf/trufflehog3#12]
Hello, I'm using this tool to scan files for secrets and importing results to sonarqube. I've wanted to move to version 2.x but importing to sonar is dependent on line numbers of findings being available. Would it be possible to add this back?

**Comment by feeltheajf** [comment]
Hi @corang 

Thanks for pointing this out! I've added `--line-numbers` parameter to include line numbers in matched strings

**Comment by abrichards5** [comment]
Thanks! we will give it a try
