### ISSUE TITLE
Generate HTML

### ISSUE THREAD

**Issue by jaikishantulswani** [feeltheajf/trufflehog3#14]
@feeltheajf Having issues while generating HTML Report, which is not properly generated, can you please let us know the proper way to generate HTML Report.

**Comment by feeltheajf** [comment]
Hi @jaikishantulswani 

Can you please elaborate, what kind of issues do you have?

Currently, there are two ways to generate an HTML report. The first is straightforward, just specify corresponding format when running scans

```
trufflehog3 -f html -o scan.html /path/to/folder
```

If you need JSON/YAML report at the same time (e.g. to pass it to some aggregation tool), you can output results in the needed format and render HTML from it later

```
trufflehog3 -f json -o scan.json /path/to/folder

trufflehog3 -R -o scan.html scan.json
```

**Comment by jaikishantulswani** [comment]
@feeltheajf thank you this helps alot :100:
