### ISSUE TITLE
Add SARIF format for output

### ISSUE THREAD

**Issue by damiencarol** [feeltheajf/trufflehog3#23]
Support Static Analysis Results Interchange Format (SARIF) Version 2.1.0 when we scan.

https://www.oasis-open.org/standard/sarifv2-1-os/

Like 
```
trufflehog3 -f sarif https://github.com/dxa4481/truffleHog.git > dojo/unittests/scans/trufflehog3/many_vulns.sarif
```

**Comment by damiencarol** [comment]
@feeltheajf could you take a look? should not be a complex modification.

**Comment by feeltheajf** [comment]
Hi @damiencarol 

Unfortunately, I have no plans to add new features to v2 since v3 is already in the works. However, I'll gladly accept PRs if you wish to contribute

**Comment by damiencarol** [comment]
I'm working on a PR to add that but as there is a merge in progress with upstream repo, I'm not sure the best approach here

**Comment by feeltheajf** [comment]
@damiencarol 

Sorry for long response. So as I'm working on v3, here is a more or less stable result JSON

https://github.com/feeltheajf/trufflehog3/blob/master/docs/examples/report.json

If you can convert it to a minimal SARIF report example, I think it will not take much time for me to form it in the code. Will it work for you?

**Comment by damiencarol** [comment]
You have many examples at https://github.com/DefectDojo/django-DefectDojo/tree/dev/dojo/unittests/scans/sarif
Like https://github.com/DefectDojo/django-DefectDojo/blob/dev/dojo/unittests/scans/sarif/taint-python-report.sarif
