### ISSUE TITLE
Request: Add a list of file extensions and/or folders to ignore

### ISSUE THREAD

**Issue by johnsaigle** [feeltheajf/trufflehog3#26]
Hi, this tool is great! I'd love to see an enhancement to ignore certain folders. It would help reduce running time and false positives.

**Comment by feeltheajf** [comment]
Hi @johnsaigle 

I believe there's such functionality already. Check out help for `--skip-paths` options and the example config 

https://github.com/feeltheajf/trufflehog3/blob/2.x/trufflehog.yaml

**Comment by johnsaigle** [comment]
Oops you're right. Sorry about that, guess I didn't read the help too closely
