### ISSUE TITLE
what does the option "--no-current" do?

### ISSUE THREAD

**Issue by rahul-ve** [feeltheajf/trufflehog3#28]
@feeltheajf 
Thank you for the tool!
Can you please clarify what "--no-current" option does?

Thanks,
Rahul

**Comment by feeltheajf** [comment]
Hi @rahul-ve 

It means skip the scan of the current state, i.e. as if it was a simple folder, not a Git repo. Scan of Git commits is controlled by `--no-history`

**Comment by rahul-ve** [comment]
Thanks @feeltheajf 

When I used:
```
no_history: false
no_current: false
```
I got some duplicates where one entry has git commit/branch info, the other one had no commit info.

When I used:
```
no_history: false
no_current: true
```
This did not have the non-git entries. 

So based on what you mentioned above: `no_current: true`  will skip the current state, that is treating it as a simple folder (as if .git folder does not exist) but will not identify any threats. Is that correct?

I guess the double negative confused me!
