### ISSUE TITLE
Detect a sha of a bootstrap css as Twitter access token

### ISSUE THREAD

**Issue by wangq13** [feeltheajf/trufflehog3#38]
I generated a R package with pkgdown. For Github Actions, I used trufflehog3 to check if any credentials are detected. The warning messages are "Twitter Access Token" and the example highlighted scripts in some html files are listed below. 

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">`

However, this is just a sha of the bootstrap css; it's not a credential. Do you happen to know how to avoid detecting this? Thanks!

FYI, the scripts I used for trufflehog3 are:
`python -m pip install trufflehog3`

`trufflehog3 -v --no-entropy . && echo "tufflehog3 secrets scan passed" `

**Comment by feeltheajf** [comment]
Hey @wangq13 

Have a look at a sample exclude config - [.trufflehog3.yml](https://github.com/feeltheajf/trufflehog3/blob/master/.trufflehog3.yml). You can use regex pattern to exclude similar issues as well or take a safer approach and just exclude this specific hash.
