### ISSUE TITLE
trufflehog3  "2.0.5" version suddenly stopped

### ISSUE THREAD

**Issue by saharora** [feeltheajf/trufflehog3#39]
I was using trufflehog3  "2.0.5" version for more then year and yesterday it suddenly breaks in our various repositories and threw an error mentioned below :
**"ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/site-packages/markupsafe/__init__.py)"**

Would you please let me know is something changes and cause of this issue?
we were also skipping some folders and some files from the scan using options --skip-paths and --skip-strings in an older version which I haven't found in the new version.

**Comment by feeltheajf** [comment]
Hey @saharora 

Unfortunately, I don't have much time for this project, so legacy versions are not really supported. Please switch to v3.x, you might want to check out [.trufflehog3.yml](https://github.com/feeltheajf/trufflehog3/blob/master/.trufflehog3.yml) config for examples on how to exclude issues by IDs, patterns, on specific paths, etc.
