### ISSUE TITLE
Pre-commit hook

### ISSUE THREAD

**Issue by Priyadhana** [feeltheajf/trufflehog3#45]
Hi, I am trying to add Trufflehog3 as a pre-commit and pre-push step. Does Trufflehog3 support pre-commit hook? I found this pre-commit sample **https://github.com/trufflesecurity/trufflehog#precommit-hook** for trufflehog but the latest version trufflehog3 does not support --fail argument and throws error.

<img width="872" alt="Screenshot 2022-12-16 at 8 11 47 PM" src="https://user-images.githubusercontent.com/48547351/208122698-45a1f9b4-ff1c-4b31-85ab-aa9de547212e.png">

Can you please guide me on how to create and fail the pre-commit step if trufflehog3 finds any issues?

**Comment by 2013kaa** [comment]
@Priyadhana Great question! I will face it soon.

**Comment by feeltheajf** [comment]
Hello there,

Right now there's no GitHub action support in trufflehog3. If you wish to contribute, please see:

https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

and an example in the original trufflehog:

https://github.com/trufflesecurity/trufflehog/blob/main/action.yml

**Comment by feeltheajf** [comment]
Closing as stale

**Comment by feeltheajf** [comment]
Closing as stale
