### ISSUE TITLE
How is this library better than the original?

### ISSUE THREAD

**Issue by Syzygianinfern0** [feeltheajf/trufflehog3#47]
I am curious as to what the differences are between this project and https://github.com/trufflesecurity/trufflehog.

Your readme states that "This is an enhanced version of the truffleHog scanner". Thanks!

**Comment by feeltheajf** [comment]
Hi @Syzygianinfern0 
The readme was written long before [trufflesecurity/trufflehog](https://github.com/trufflesecurity/trufflehog) was completely rewritten in Go, so it's hard to say what the real difference is now. At that time, [trufflesecurity/trufflehog](https://github.com/trufflesecurity/trufflehog) wasn't supported much (see also #24), while I needed some major features to be implemented, such as faster scans using multiprocessing and a convenient, yet flexible configuration for excluding false positives (it's all mentioned in the readme).

At a first glance, it seems that [trufflesecurity/trufflehog](https://github.com/trufflesecurity/trufflehog) still doesn't have an exclude configuration similar to what this version has. Moreover, adding new rules now requires you to write the actual Go code, meaning you should either 
* merge it into the public repo, which might not be acceptable in certain cases 
* fork and maintain your own copy of the repo, which adds maintenance overhead

 Of course, the choice is yours and it depends on your requirements. If I may suggest, [gitleaks](https://github.com/gitleaks/gitleaks) is a nice option as well.

**Comment by Syzygianinfern0** [comment]
@feeltheajf Thanks!
