### ISSUE TITLE
trufflehog3 is not able to findout private key if it doesn't have keyword like RSA, EC etc.

### ISSUE THREAD

**Issue by ankitloud** [feeltheajf/trufflehog3#48]
tTrufflehog3 is able to find out below type of key-
-----BEGIN RSA PRIVATE KEY-----
But not able to find like below
-----BEGIN PRIVATE KEY-----

**Comment by feeltheajf** [comment]
Hi @ankitloud 
The default rules can be found here: https://github.com/feeltheajf/trufflehog3/blob/master/trufflehog3/static/rules.yml. You can customise them to your liking and pass to trufflehog using `-r/--rules` option. Also, from my experience, private keys are usually detected by high entropy checks.

**Comment by ankitloud** [comment]
Yes, did the same but it would be good if you add the rule by default
