### ISSUE TITLE
Pattern matching to exclude false positives with trufflehog3

### ISSUE THREAD

**Issue by sateeshmaheshwaram** [feeltheajf/trufflehog3#49]
trufflehog3 reporting too many false postives, it would be better to have option to feed pattern matching / checks to avoid false positives. Tried config and excluding it works for known values / secrets, looking for option to generic pattern /regex matching.

**Comment by feeltheajf** [comment]
Hi @sateeshmaheshwaram 
`pattern` property in `.trufflehog3.yml` is interpreted as Python regex. Give it a try and let me know if it doesn't work as you expect.
