### ISSUE TITLE
Analyzing the contents within a variable.

### ISSUE THREAD

**Issue by sateeshmaheshwaram** [feeltheajf/trufflehog3#58]
Can you assist in exploring methods for adding file contents to a variable and then utilizing trufflehog3 to scan for any sensitive information?

Suppose I have automation runbooks (both .ps1 and .py files) that I need to check for any sensitive information. I'm considering extracting the contents of these files into variables within a script and then using those variables as arguments for trufflehog3 to conduct a scan.

**Comment by feeltheajf** [comment]
Hello, @sateeshmaheshwaram 

Here's a minimal example to get you started:

```python
from trufflehog3 import DEFAULT_RULES_FILE
from trufflehog3.core import load_rules
from trufflehog3.models import File
from trufflehog3.render import text
from trufflehog3.search import search


content = """# Test content
password = "570a60db1d410c81e7ad8dfc7fdb429c"
print(password)
"""

rules = load_rules(DEFAULT_RULES_FILE)
issues = search(File(path="", content=content), rules=rules)
print(text(issues))
```
